use crate::{registry::{expand,Tool,TOOLS_ROOT},workspace::LaunchPaths};
use std::{fs,path::{Path,PathBuf},process::Command};
use sha2::{Digest,Sha256};
use tauri_plugin_opener::OpenerExt;

pub fn execute(tool:&Tool,action:&str,app:&tauri::AppHandle,paths:Option<&LaunchPaths>)->Result<String,String>{match action{"launch"=>launch(tool,app,paths),"folder"=>open_folder(tool,app),_=>Err("This action is not allowed".into())}}
fn launch(tool:&Tool,app:&tauri::AppHandle,paths:Option<&LaunchPaths>)->Result<String,String>{
 if tool.r#type=="web"{if tool.url.is_some(){return Err("Remote web tools are disabled in this build".into())}let local=trusted_executable(tool)?;app.opener().open_path(local.to_string_lossy(),None::<&str>).map_err(|_|"Could not open the local web tool".to_string())?;return Ok(format!("Opened offline {}",tool.name))}
 let executable_path=trusted_executable(tool)?;let registered_executable=shell_path(&executable_path);let working_directory=executable_path.parent().ok_or("Configured executable has no parent directory")?;let shell_working_directory=PathBuf::from(shell_path(working_directory));let configured_args=tool.arguments.clone().unwrap_or_default();let (executable,args)=if tool.r#type=="python"{let launcher=trusted_python_launcher()?;let args=std::iter::once(registered_executable).chain(configured_args).collect();(shell_path(&launcher),args)}else{(registered_executable,configured_args)};apply_process_env(paths);let console=matches!(tool.r#type.as_str(),"cli"|"python"|"powershell"|"bash");let wrapper=if console{paths.map(|p|console_wrapper(&executable,&args,p)).transpose()?}else{None};
 if tool.requires_admin.unwrap_or(false){elevated_launch(&executable,&args,console,Some(&shell_working_directory),wrapper.as_deref())?;return Ok(format!("Requested administrator approval for {}",tool.name))}
 if console{let mut command=Command::new("cmd.exe");command.args(["/D","/K"]);if let Some(script)=wrapper{command.arg(script);}else{command.arg(&executable).args(args);}command.current_dir(working_directory).spawn().map_err(|e|e.to_string())?;}else if executable.to_ascii_lowercase().ends_with(".bat")||executable.to_ascii_lowercase().ends_with(".cmd"){Command::new("cmd.exe").args(["/D","/C"]).arg(&executable).args(args).current_dir(working_directory).spawn().map_err(|e|e.to_string())?;}else{Command::new(&executable).args(args).current_dir(working_directory).spawn().map_err(|e|e.to_string())?;}Ok(format!("Launched {}",tool.name))
}
#[cfg(target_os="windows")]
fn elevated_launch(executable:&str,args:&[String],console:bool,working_directory:Option<&Path>,wrapper:Option<&Path>)->Result<(),String>{use std::{ffi::OsStr,os::windows::ffi::OsStrExt,ptr::{null,null_mut}};use windows_sys::Win32::UI::{Shell::ShellExecuteW,WindowsAndMessaging::SW_SHOWNORMAL};fn wide(value:&str)->Vec<u16>{OsStr::new(value).encode_wide().chain(Some(0)).collect()}fn quote(value:&str)->String{format!("\"{}\"",value.replace('"',"\\\""))}let verb=wide("runas");let (target,params)=if console{let command=wrapper.map(|p|quote(&p.to_string_lossy())).unwrap_or_else(||std::iter::once(quote(executable)).chain(args.iter().map(|a|quote(a))).collect::<Vec<_>>().join(" "));("cmd.exe".to_string(),format!("/D /K call {command}"))}else{(executable.to_string(),args.iter().map(|a|quote(a)).collect::<Vec<_>>().join(" "))};let file=wide(&target);let parameters=wide(&params);let directory=working_directory.map(|path|wide(&path.to_string_lossy()));let directory_ptr=directory.as_ref().map_or(null(),|value|value.as_ptr());let result=unsafe{ShellExecuteW(null_mut(),verb.as_ptr(),file.as_ptr(),parameters.as_ptr(),directory_ptr,SW_SHOWNORMAL)} as isize;if result<=32{Err(format!("Windows elevation was denied or failed (code {result})"))}else{Ok(())}}
#[cfg(not(target_os="windows"))]
fn elevated_launch(_executable:&str,_args:&[String],_console:bool,_working_directory:Option<&Path>,_wrapper:Option<&Path>)->Result<(),String>{Err("Elevation is only supported on Windows".into())}
fn quote_cmd(value:&str)->String{format!("\"{}\"",value.replace('"',"\"\""))}
fn apply_process_env(paths:Option<&LaunchPaths>){if let Some(p)=paths{std::env::set_var("DFIR_CASE",&p.case);std::env::set_var("DFIR_EVIDENCE",&p.evidence);std::env::set_var("DFIR_OUTPUT",&p.output)}}
fn console_wrapper(executable:&str,args:&[String],paths:&LaunchPaths)->Result<PathBuf,String>{let script=PathBuf::from(&paths.output).join("launch.cmd");let invocation=std::iter::once(quote_cmd(executable)).chain(args.iter().map(|a|quote_cmd(a))).collect::<Vec<_>>().join(" ");let case=batch_value(&paths.case);let evidence=batch_value(&paths.evidence);let output=batch_value(&paths.output);let body=format!("@echo off\r\nset \"DFIR_CASE={case}\"\r\nset \"DFIR_EVIDENCE={evidence}\"\r\nset \"DFIR_OUTPUT={output}\"\r\ncall {invocation}\r\necho.\r\necho Active case paths:\r\nset DFIR_\r\necho.\r\n");fs::write(&script,body).map_err(|e|format!("Could not create CLI launcher: {e}"))?;Ok(script)}
fn batch_value(value:&str)->String{value.replace('%',"%%").replace('"',"\"\"")}
fn shell_path(path:&Path)->String{let value=path.to_string_lossy();if let Some(rest)=value.strip_prefix(r"\\?\UNC\"){format!(r"\\{rest}")}else{value.strip_prefix(r"\\?\").unwrap_or(&value).to_string()}}
pub(crate) fn trusted_executable(tool:&Tool)->Result<PathBuf,String>{let raw=tool.executable.as_ref().ok_or("Executable is not configured")?;let expanded=PathBuf::from(expand(raw));if !expanded.is_file(){return Err("The registered tool is not installed".into())}let root=PathBuf::from(TOOLS_ROOT).canonicalize().map_err(|_|"The approved tools directory is unavailable")?;let executable=expanded.canonicalize().map_err(|_|"Could not verify the registered tool")?;if !executable.starts_with(&root){return Err("The registered tool is outside the approved tools directory".into())}let meta=fs::symlink_metadata(&expanded).map_err(|_|"Could not verify the registered tool")?;if meta.file_type().is_symlink()||!meta.is_file(){return Err("Linked tool executables are not allowed".into())}let allowed=match tool.r#type.as_str(){"application"|"portable"|"cli"=>["exe","com","bat","cmd"].contains(&executable.extension().and_then(|v|v.to_str()).unwrap_or("").to_ascii_lowercase().as_str()),"python"=>executable.extension().and_then(|v|v.to_str()).is_some_and(|v|v.eq_ignore_ascii_case("py")),"powershell"=>executable.extension().and_then(|v|v.to_str()).is_some_and(|v|v.eq_ignore_ascii_case("ps1")),"bash"=>true,"web"=>["html","htm"].contains(&executable.extension().and_then(|v|v.to_str()).unwrap_or("").to_ascii_lowercase().as_str()),_=>false};if !allowed{return Err("The registered tool has an unexpected file type".into())}verify_hash(&tool.id,&executable)?;Ok(executable)}
fn verify_hash(tool_id:&str,path:&Path)->Result<(),String>{let manifest:std::collections::HashMap<String,String>=serde_json::from_str(include_str!("../../config/tool-hashes.json")).map_err(|_|"The embedded integrity manifest is invalid")?;let expected=manifest.get(tool_id).ok_or("This installed tool has no approved integrity hash")?;let bytes=fs::read(path).map_err(|_|"Could not read the registered tool for integrity checking")?;let actual=format!("{:x}",Sha256::digest(&bytes));if actual.eq_ignore_ascii_case(expected){Ok(())}else{Err("The registered tool failed its integrity check".into())}}
fn trusted_python_launcher()->Result<PathBuf,String>{let configured=PathBuf::from(r"C:\DFIR\Tools\ThreatHunting\Zircolite\3.8.1\runtime\Scripts\python.exe");let meta=fs::symlink_metadata(&configured).map_err(|_|"The approved Python runtime is not installed")?;if meta.file_type().is_symlink()||!meta.is_file(){return Err("The approved Python runtime is not a normal file".into())}let launcher=configured.canonicalize().map_err(|_|"Could not verify the approved Python runtime")?;let tools=PathBuf::from(TOOLS_ROOT).canonicalize().map_err(|_|"Could not verify the approved tools directory")?;if !launcher.starts_with(tools){return Err("The Python runtime is outside the approved tools directory".into())}verify_hash("python-runtime",&launcher)?;Ok(launcher)}
pub fn elevate_memory_helper(case_id:&str)->Result<(),String>{crate::workspace::validate_case_id(case_id)?;let current=std::env::current_exe().map_err(|_|"Could not locate the application executable")?;let executable=current.canonicalize().map_err(|_|"Could not verify the application executable")?;elevated_launch(&executable.to_string_lossy(),&["--memory-acquisition-helper".into(),case_id.into()],false,executable.parent(),None)}
fn open_folder(tool:&Tool,app:&tauri::AppHandle)->Result<String,String>{let executable=trusted_executable(tool)?;let parent=executable.parent().ok_or("Configured path has no parent directory")?;app.opener().open_path(parent.to_string_lossy(),None::<&str>).map_err(|_|"Could not open the tool folder".to_string())?;Ok(format!("Opened folder for {}",tool.name))}
